# For example, setting:
# GMAIL_USERNAME: 'Your_Gmail_Username'
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
GIT_APP_ID: '3d0dc6145cf736a90534'
GIT_APP_SECRET: 'd6f0c6c48dd2007dafa580d7a1b2a8887987f994'
MANDRILL_USERNAME: 'jtomas1993@gmail.com'
MANDRILL_API_KEY: 'qVBaSHDiNBcLED9rYPqZXw'
